---
title: "Team 1 Mid-term Project"
author: "Team 1 (Names: Adam Kritz; Huang He..."
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---



```{r init, include=F}
# The package "ezids" (EZ Intro to Data Science) includes a lot of the helper functions we developed for the course. 
# Some of the frequently used functions are loadPkg(), xkabledply(), xkablesummary(), uzscale(), etc.
library(ezids)
```

# Midterm Project

## Importing the Data

```{r setup, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```

```{r read the dataset}
diamonds = data.frame(read.csv("diamonds.csv"))
summary(diamonds)
str(diamonds)
diamonds$color = factor(diamonds$color, order=T, levels = c('D', 'E', 'F', 'G', 'H', 'I', 'J'))
diamonds$clarity = factor(diamonds$clarity, order=T, levels = c('I1', 'SI2', 'SI1', 'VS2', 'VS1', 'VVS2', 'VVS1', 'IF'))
diamonds$cut = factor(diamonds$cut, order=T, levels = c('Fair', 'Good', 'Very Good', 'Premium', 'Ideal'))
colnames(diamonds)[1] = "ID"
colnames(diamonds)
summary(diamonds)
```

## Diamonds of all price

### Distribution of each variables

#### price
```{r}
library(ggplot2)
# histogram
p = ggplot(diamonds,aes(x=price)) + 
  geom_histogram(breaks = seq(300,18900,100),fill = "red",color = "black",alpha = 0.3) + labs(title = "Distribution of Price", x = "Price",y = "frequency")
p  + theme_bw()
# boxplot
p = ggplot(diamonds,aes(y=price)) + 
  geom_boxplot(colour="orange", fill="#7777cc", outlier.colour="red", outlier.shape=8, outlier.size=4) + 
  labs(title = "Distribution of Price")
p + theme_bw() + theme(panel.grid=element_blank())
# QQ-plot
qqnorm(diamonds$price, main="Q-Q plot of Price", col = 'blue', ylab = 'Price') 
qqline(diamonds$price)

```


#### carat
```{r}
# histogram
p = ggplot(diamonds,aes(x=carat)) + 
  geom_histogram(breaks = seq(0.2,5.1,0.1),fill = "red",color = "black",alpha = 0.3) + labs(title = "Distribution of Carat", x = "Carat",y = "frequency")
p  + theme_bw()
# boxplot
p = ggplot(diamonds,aes(y=carat)) + 
  geom_boxplot(colour="orange", fill="#7777cc", outlier.colour="red", outlier.shape=8, outlier.size=4) + 
  labs(title = "Distribution of Carat")
p + theme_bw() + theme(panel.grid=element_blank())
# QQ-plot
qqnorm(diamonds$carat, main="Q-Q plot of Carat", col = 'blue', ylab = 'Carat') 
qqline(diamonds$carat)
```

#### table
```{r}
# histogram
p = ggplot(diamonds,aes(x=table)) + 
  geom_histogram(breaks = seq(42,96,1),fill = "red",color = "black",alpha = 0.3) + labs(title = "Distribution of Table", x = "Table",y = "frequency")
p  + theme_bw()
# boxplot
p = ggplot(diamonds,aes(y=table)) + 
  geom_boxplot(colour="orange", fill="#7777cc", outlier.colour="red", outlier.shape=8, outlier.size=4) + 
  labs(title = "Distribution of Table")
p + theme_bw() + theme(panel.grid=element_blank())
# QQ-plot
qqnorm(diamonds$table, main="Q-Q plot of Table", col = 'blue', ylab = 'Table') 
qqline(diamonds$table)
```

#### depth
```{r}
# histogram
p = ggplot(diamonds,aes(x=depth)) + 
  geom_histogram(breaks = seq(43,79,0.5),fill = "red",color = "black",alpha = 0.3) + labs(title = "Distribution of Depth", x = "depth",y = "frequency")
p  + theme_bw()
# boxplot
p = ggplot(diamonds,aes(y=depth)) + 
  geom_boxplot(colour="orange", fill="#7777cc", outlier.colour="red", outlier.shape=8, outlier.size=4) + 
  labs(title = "Distribution of Depth")
p + theme_bw() + theme(panel.grid=element_blank())
# QQ-plot
qqnorm(diamonds$depth, main="Q-Q plot of Depth", col = 'blue', ylab = 'Depth') 
qqline(diamonds$depth)
```



```{r}


```






