---
title: "Team 1 Mid-term Project"
author: "Team 1 (Names: Adam Kritz; Huang He..."
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---



```{r init, include=F}
# The package "ezids" (EZ Intro to Data Science) includes a lot of the helper functions we developed for the course. 
# Some of the frequently used functions are loadPkg(), xkabledply(), xkablesummary(), uzscale(), etc.
library(ezids)
```

# Midterm Project

## Importing the Data

```{r setup, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```

```{r read the dataset}
diamonds = data.frame(read.csv("diamonds.csv"))
summary(diamonds)
str(diamonds)
diamonds$color = factor(diamonds$color, order=T, levels = c('D', 'E', 'F', 'G', 'H', 'I', 'J'))
diamonds$clarity = factor(diamonds$clarity, order=T, levels = c('I1', 'SI2', 'SI1', 'VS2', 'VS1', 'VVS2', 'VVS1', 'IF'))
diamonds$cut = factor(diamonds$cut, order=T, levels = c('Fair', 'Good', 'Very Good', 'Premium', 'Ideal'))
colnames(diamonds)[1] = "ID"
colnames(diamonds)
summary(diamonds)
```

## EDA section - Adam (in progress)

### diamonds summary

```{r, results = 'markup'}
xkablesummary(diamonds, title = "Summary of Diamonds")
```


### Categorical Data Exploration

```{r categorical variables}
barplot(table(diamonds$cut), col = c(2, 3, 4, 7, 6), main = 'Barplot of Cut', xlab = "Cut", ylab = "Frequency")
barplot(table(diamonds$color), col = c(2, 3, 4, 7, 6, 8, 9), main = 'Barplot of Color', xlab = "Color", ylab = "Frequency")
barplot(table(diamonds$clarity), col = c(2, 3, 4, 7, 6, 8, 9, 5), main = 'Barplot of Clarity', xlab = "Clarity", ylab = "Frequency")

cut_count = dplyr::count(diamonds, cut)
colnames(cut_count)[colnames(cut_count) == 'cut'] <- 'Cut'
cut_count$n = cut_count$n/sum(cut_count$n)

loadPkg("ggplot2")

ggplot(cut_count, aes(x = "", y = n, fill = Cut)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  geom_text(size = 4, aes(label = paste0(round(n, 2), "%")), position = position_stack(vjust = 0.5))+
  scale_fill_manual(values = c(6, 7, 8, 3, 4))+
  labs(title='Pie Chart of Cut')
  
```

### diamonds numerical text summaries

```{r numerical variables text}
mean(diamonds$depth)
sd(diamonds$depth)

mean(diamonds$table)
sd(diamonds$table)

mean(diamonds$carat)
sd(diamonds$carat)

mean(diamonds$price)
sd(diamonds$price)
```

### Numerical Data Exploration

```{r numerical variables}
# removed weird outliers, note in slides
diaNO = subset(diamonds, x > 0 & y > 0 & z > 0 & y <30 & z <30)
ggplot(diaNO, aes(x, y, color=z)) +
  geom_point(size = 8, alpha = 0.6) +
  ggtitle('Y versus X versus Z for Diamonds') +
  scale_color_gradient2(midpoint = 5, low="blue", mid="green", high="red")

ggplot(diamonds, aes(y=table)) + 
  geom_histogram(col="black", 
                 fill="red", 
                  alpha = .8,
                 binwidth = 1.5) +
  labs(title='Barplot of Table') +
  coord_flip() +
  labs(y="Table", x="Frequency")

ggplot(diamonds, aes(y=depth)) + 
  geom_histogram(col="black", 
                 fill="green", 
                  alpha = .8,
                 binwidth = 1) +
  coord_flip() +
  labs(title='Barplot of Depth') +
  labs(y="Depth", x="Frequency")

ggplot(diamonds, aes(y=carat)) + 
  geom_boxplot() + 
  geom_boxplot(colour="black", fill="orange", outlier.colour="orange", outlier.size=5, alpha = 0.8) +
  labs(title = 'Boxplot of Carat')+
  labs(y="Carat")
```

### Price Exploration

```{r d10kp price}
ggplot(diamonds, aes(y=price)) + 
  geom_boxplot() + 
  geom_boxplot(colour="black", fill="blue", outlier.colour="blue", outlier.size=1, alpha = 0.8) +
  labs(title = 'Boxplot of Price')

ggplot(diamonds, aes(y=price)) + 
  geom_histogram(col="black", 
                 fill="blue", 
                  alpha = .8,
                 binwidth = 300) +
  coord_flip() +
  labs(title='Barplot of Price') +
  labs(y="Price", x="Frequency")

qqnorm(diamonds$price, main="Q-Q plot of Price", col = 'blue', ylab = 'Price') 
qqline(diamonds$price)

```

## caterigocal affect on price - Solomon


## continious variable affect on price - Suhas


```{r}
# Creating a subset of continuous variables, calculating the correlation matrix and making the corrplot to identify the strongest relationships between continuous variables.

diamonds_continuous = subset(diamonds, select = c("carat", "depth", "table", "price", "x", "y", "z"))
loadPkg("corrplot")
diamonds_continuous_cor= cor(diamonds_continuous)
corrplot(diamonds_continuous_cor, method= "number")

```

## categorical variable affect on cut - Huang

```{r}
```
